### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by lefmarna** [lefmarna/furima-35067#9]
# 自身のフリマアプリのURL
https://furima-35067.herokuapp.com/

## Basic認証のIDとパスワード |  
ID：admin
パスワード：2222

## 出品者用のメールアドレスとパスワード
test@test.be
66M2qamWm4dENACwVxx

## 購入者用のメールアドレスとパスワード
example@example.be
28VhKNLGwvikMcZt4Fj

**Comment by snkw-works** [comment]
@lefmarna さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン状態のユーザーは、出品ボタンをクリックすると商品出品ページへ遷移できるよう修正しましょう**
現状、出品ボタンをクリックしても商品出品ページへ遷移できない状態です。
※今回は「 http://furima-35067.herokuapp.com/items/new 」のURLを直接入力して挙動確認をしております。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by lefmarna** [comment]
@snkw-works さん、ご確認ありがとうございます。

商品出品ページに遷移するというのはトップページのことで合っていますよね？　こちらでも試したのですが挙動は問題ないと思われます。
重い画像を添付するとアップロードに時間がかかって遷移が遅くなるので、それが原因かなと思うのですがどうでしょうか？

もう少し詳細をお伺いしたいです。

**Comment by chobi555** [comment]
レビュー依頼ありがとうございます！
こちら挙動確認になりますので下記URLより再度投稿していただくようお願いいたします。

https://docs.google.com/forms/d/e/1FAIpQLSe08G_NmjDTnmZwvplaR5dUh_zUdqH4B4T60lRDIGpzxqBJAg/viewform

**Comment by snkw-works** [comment]
@lefmarna さん、お問い合わせいただきありがとうございます。

説明不足で大変失礼いたしました。
> 現状、出品ボタンをクリックしても商品出品ページへ遷移できない状態です。

こちら、トップページの右下に表示されている「出品する」ボタンのことでございます。
<img width="1440" alt="スクリーンショット_2021-04-05_17_02_09" src="https://user-images.githubusercontent.com/54050089/113552212-c5704d00-9630-11eb-8c54-87d4f632cfc8.png">

本番環境では、トップページ右下の「出品する」ボタンをクリックしても、商品出品ページに遷移することができませんでした。
念の為、挙動確認動画も添付いたします。（こちらわかりづらいですが、一度出品するボタンをクリックしております。）
https://user-images.githubusercontent.com/54050089/113552442-1ed87c00-9631-11eb-8fbf-98ac9515ab9d.mov

以上、ご確認いただけますと幸いです。よろしくお願いいたします。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします。
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by lefmarna** [comment]
返信ありがとうございます。
いつも『新規投稿商品』から投稿していたためボタンの存在に気づいていませんでした。

修正いたしましたので、改めてレビューよろしくおねがいします。

**Comment by takumi0530** [comment]
@lefmarna さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/113559756-e8086300-963c-11eb-91c9-10814dedf1b0.png)
